# Generated by Django 4.0.6 on 2022-08-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_alter_block_day_alter_block_total_block_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block7_total_stoppage',
            field=models.IntegerField(blank=True, null=True, verbose_name='جمع توقفات'),
        ),
        migrations.AlterField(
            model_name='block',
            name='block8_total_stoppage',
            field=models.IntegerField(blank=True, null=True, verbose_name='جمع توقفات'),
        ),
        migrations.AlterField(
            model_name='block',
            name='dryer_total_stoppage',
            field=models.IntegerField(blank=True, null=True, verbose_name='جمع توقفات'),
        ),
    ]
