# Generated by Django 4.0.6 on 2022-08-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_alter_block_block7_total_stoppage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='betogips_inventory',
            field=models.IntegerField(blank=True, null=True, verbose_name='دسته بندی بتو گیپس'),
        ),
        migrations.AddField(
            model_name='block',
            name='betogips_wased',
            field=models.IntegerField(blank=True, null=True, verbose_name='خشک کن بتو گیپس'),
        ),
    ]
