# Generated by Django 4.0.6 on 2022-08-16 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('block', '0004_block_betogips_inventory_block_betogips_wased'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده'),
        ),
        migrations.AddField(
            model_name='block',
            name='published_date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ ثبت'),
        ),
    ]
