# Generated by Django 4.0.6 on 2022-08-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_block_author_block_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='published_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='تاریخ ثبت'),
        ),
    ]
