# Generated by Django 4.0.6 on 2022-10-14 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ten_Sieve_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(auto_now=True)),
                ('year', models.IntegerField(max_length=5)),
                ('month', models.IntegerField(max_length=2)),
                ('day', models.IntegerField(max_length=2)),
                ('sieve_40', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sieve_63', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sieve_90', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sieve_100', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sieve_200', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sieve_300', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sieve_400', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sieve_500', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sieve_600', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sieve_1000', models.DecimalField(decimal_places=2, max_digits=4)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
