# Generated by Django 4.0.6 on 2022-10-21 08:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ten_sieve_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ten_Sieve_Analysis',
            new_name='Ten_Sieve_Analysis_Model',
        ),
    ]
