# Generated by Django 4.0.6 on 2023-02-17 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ultrax_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Target_Product', models.CharField(choices=[('k-', 'k-'), ('k-1', 'k-1'), ('k-2', 'k-2')], max_length=6)),
                ('published_date', models.DateField(auto_now=True)),
                ('year', models.IntegerField(max_length=4)),
                ('month', models.IntegerField(max_length=4)),
                ('day', models.IntegerField(max_length=4)),
                ('hour', models.IntegerField(max_length=2)),
                ('line_qc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('office_qa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('kiln', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dif_line_kiln', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dif_qa_kiln', models.DecimalField(decimal_places=2, max_digits=4)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
