# Generated by Django 4.0.6 on 2022-09-16 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QC_Block_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(auto_now=True)),
                ('year', models.IntegerField(max_length=4)),
                ('month', models.IntegerField(max_length=2)),
                ('day', models.IntegerField(max_length=2)),
                ('date_production', models.DateField()),
                ('date_sampling', models.DateField()),
                ('type_block', models.CharField(choices=[('OR7', 'OR7'), ('OR8', 'OR8')], max_length=100)),
                ('thickness', models.IntegerField()),
                ('length', models.DecimalField(decimal_places=1, max_digits=4)),
                ('height', models.IntegerField(max_length=2)),
                ('flatness', models.CharField(choices=[('OK', 'OK'), ('FALSE', 'FALSE')], max_length=8)),
                ('mass', models.DecimalField(decimal_places=2, max_digits=4)),
                ('surface_mass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('density', models.DecimalField(decimal_places=2, max_digits=6)),
                ('water_absorption', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bending_strength', models.DecimalField(decimal_places=2, max_digits=4)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('non_conformity', models.CharField(blank=True, max_length=1000, null=True)),
                ('action', models.CharField(blank=True, max_length=1000, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
