# Generated by Django 4.0.6 on 2022-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreport',
            name='day',
            field=models.CharField(blank=True, choices=[('شنبه', 'شنبه'), ('یک شنبه', 'یک شنبه'), ('دو شنبه', 'دو شنبه'), ('سه شنبه', 'سه شنبه'), ('چهار شنبه', 'چهار شنبه'), ('پنج شنبه', 'پنج شنبه'), ('چمعه', 'جمعه')], max_length=99999999, null=True),
        ),
    ]
