# Generated by Django 4.0.6 on 2022-08-23 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_report', '0002_alter_productreport_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreport',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده'),
        ),
    ]
