# Generated by Django 4.0.6 on 2023-04-13 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flexural_Bending_Strength_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Published_Date', models.DateField(auto_now=True)),
                ('year', models.IntegerField(max_length=4)),
                ('month', models.IntegerField(max_length=2)),
                ('day', models.IntegerField(max_length=2)),
                ('code', models.CharField(choices=[('B', 'B'), ('B1', 'B1')], max_length=3)),
                ('f_flex', models.IntegerField(max_length=3)),
                ('fm_flex', models.IntegerField(max_length=3)),
                ('flexural_strength', models.DecimalField(decimal_places=2, max_digits=4)),
                ('f_compress', models.IntegerField(max_length=3)),
                ('fm_compress', models.IntegerField(max_length=3)),
                ('compressive_strength', models.DecimalField(decimal_places=2, max_digits=4)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
        ),
    ]
