# Generated by Django 4.0.6 on 2023-04-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexural_bending_strength', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexural_bending_strength_model',
            old_name='Published_Date',
            new_name='published_date',
        ),
    ]
