# Generated by Django 4.0.6 on 2022-09-28 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QC_Block_Stucco_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(auto_now=True)),
                ('month', models.IntegerField(max_length=2)),
                ('day', models.IntegerField(max_length=2)),
                ('hour', models.IntegerField(max_length=2)),
                ('crystal_water_stucco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('einstrumenge', models.IntegerField(max_length=3)),
                ('water_gypsum_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('initial_setting_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('final_setting_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('retained_200', models.DecimalField(decimal_places=2, max_digits=4)),
                ('retained_500', models.DecimalField(decimal_places=2, max_digits=4)),
                ('non_conformity', models.CharField(blank=True, max_length=1000, null=True)),
                ('action', models.CharField(blank=True, max_length=1000, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
