# Generated by Django 4.0.6 on 2022-11-03 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blane_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=5)),
                ('published_date', models.DateField(auto_now=True)),
                ('blane', models.IntegerField(max_length=6)),
                ('initial_setting_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('final_setting_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
