# Generated by Django 4.0.6 on 2022-11-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blane', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blane_model',
            name='published_date',
            field=models.DateField(),
        ),
    ]
