# Generated by Django 4.0.6 on 2022-09-05 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(auto_now=True)),
                ('year', models.IntegerField(max_length=4)),
                ('month', models.IntegerField(max_length=2)),
                ('day', models.IntegerField(max_length=2)),
                ('hour', models.IntegerField(max_length=2)),
                ('inlet_feed', models.CharField(choices=[('خاک مواد خام', 'خاک مواد خام'), ('خاک مواد خام', 'خاک مواد خام')], max_length=100)),
                ('bag_number_2', models.IntegerField(max_length=4)),
                ('bag_number', models.DateField()),
                ('free_moisture_filterdust', models.DecimalField(decimal_places=2, max_digits=4)),
                ('crystal_water_filterdust', models.DecimalField(decimal_places=2, max_digits=4)),
                ('purity_filterdust', models.DecimalField(decimal_places=2, max_digits=4)),
                ('free_moisture_nealit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('retained_on_63_μm', models.DecimalField(decimal_places=2, max_digits=4)),
                ('retained_on_200_μm', models.DecimalField(decimal_places=2, max_digits=4)),
                ('retained_on_500_μm', models.DecimalField(decimal_places=2, max_digits=4)),
                ('blaine_Nealit', models.IntegerField(validators=[django.core.validators.MinValueValidator(6000, 'enter a number bigger than 6000')])),
                ('blaine_filterdust', models.IntegerField()),
                ('blaine_after_mill', models.IntegerField()),
                ('remarks', models.CharField(max_length=700)),
            ],
        ),
    ]
