# Generated by Django 4.0.6 on 2022-09-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control_nealit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QualityControl',
            new_name='QualityControlModel',
        ),
    ]
