# Generated by Django 4.0.6 on 2022-09-05 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quality_control_nealit', '0002_rename_qualitycontrol_qualitycontrolmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycontrolmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
