# Generated by Django 4.0.6 on 2022-09-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control_nealit', '0003_qualitycontrolmodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualitycontrolmodel',
            old_name='retained_on_200_μm',
            new_name='retained_on_200',
        ),
        migrations.RenameField(
            model_name='qualitycontrolmodel',
            old_name='retained_on_500_μm',
            new_name='retained_on_500',
        ),
        migrations.RenameField(
            model_name='qualitycontrolmodel',
            old_name='retained_on_63_μm',
            new_name='retained_on_63',
        ),
    ]
