# Generated by Django 3.2.3 on 2021-06-30 13:00

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('einstrumenge', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(120, 'enter a number in range [120-160]'), django.core.validators.MaxValueValidator(160, 'enter a number in range [120-160]')], verbose_name='ملات')),
                ('free_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='رطوبت آزاد')),
                ('crystal_water_rawmat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(18.0, 'enter a number in range [18-20]'), django.core.validators.MaxValueValidator(20.0, 'enter a number in range [18-20]')], verbose_name='آب کریستال مواد خام')),
                ('purity_rm', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خلوص مواد خام')),
                ('crystal_water_stucco', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(4.0, 'enter a number in range [4-7]'), django.core.validators.MaxValueValidator(7.0, 'enter a number in range [4-7]')], verbose_name='آب کریستال گچ')),
                ('water_gypsum_ratio', models.DecimalField(decimal_places=2, help_text='this is an error message1', max_digits=3, validators=[django.core.validators.MinValueValidator(0.5, 'enter a number in range [0.5-1]'), django.core.validators.MaxValueValidator(1.0, 'enter a number in range [0.5-1]')], verbose_name='نسبت آب به گچ')),
                ('initial_setting_time', models.DurationField(help_text='[MM]:[ss] format', verbose_name='گیرش اولیه')),
                ('final_setting_time', models.DurationField(blank=True, verbose_name='گیرش ثانویه')),
                ('retained_63_micron', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(20.0, 'enter a number in range [20-40]'), django.core.validators.MaxValueValidator(40.0, 'enter a number in range [20-40]')], verbose_name='الک 63 میکرون')),
                ('retained_200_micron', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(2.0, 'enter a number in range [2-20]'), django.core.validators.MaxValueValidator(20.0, 'enter a number in range [2-20]')], verbose_name='الک 200 میکرون')),
                ('retained_500_micron', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'enter a number in range [0-9]'), django.core.validators.MaxValueValidator(9.0, 'enter a number in range [0-9]')], verbose_name='الک 500 میکرون')),
                ('soluble_anhydrite', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='انیدریت محلول')),
                ('hemihydrate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='همی هیدرات')),
                ('low_solubility_anhydrite', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='انیدریت کم محلول')),
                ('non_conformity', models.BooleanField(default=False, verbose_name='عدم انطباق')),
                ('nonconf_P6', models.BooleanField(default=False, editable=django.db.models.expressions.When(non_conformity=True), verbose_name='عدم انطباق الک 63 میکرون')),
                ('nonconf_P5', models.BooleanField(default=False, editable=django.db.models.expressions.When(non_conformity=True), verbose_name='عدم انطباق الک 500 میکرون')),
                ('nonconf_P2', models.BooleanField(default=False, editable=django.db.models.expressions.When(non_conformity=True), verbose_name='عدم انطباق الک 200 میکرون')),
                ('nonconf_IS', models.BooleanField(default=False, editable=django.db.models.expressions.When(non_conformity=True), verbose_name='عدم انطباق گیرش اولیه')),
                ('nonconf_FS', models.BooleanField(default=False, editable=django.db.models.expressions.When(non_conformity=True), verbose_name='عدم انطباق گیرش ثانویه')),
                ('nonconf_EI', models.BooleanField(default=False, editable=django.db.models.expressions.When(non_conformity=True), verbose_name='عدم انطباق وزن ملات')),
                ('nonconf_FM', models.BooleanField(default=False, editable=django.db.models.expressions.When(non_conformity=True), verbose_name='عدم انطباق رطوبت آزاد')),
                ('nonconf_CS', models.BooleanField(default=False, editable=django.db.models.expressions.When(non_conformity=True), verbose_name='عدم انطباق آب کریستال گچ')),
                ('burner_sp_change', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='تغییر دمای مشعل')),
                ('remarks', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='تاریخ ثبت داده')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.action', verbose_name='تعیین تکلیف')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('call_to_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_to_operator', to=settings.AUTH_USER_MODEL, verbose_name='تماس با اپراتور')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.hour', verbose_name='ساعت آزمایش')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.line', verbose_name='خط')),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.quarry', verbose_name='معدن')),
                ('product_silo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.silo', verbose_name='محصول به سیلوی')),
                ('quarter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.quarter')),
            ],
        ),
    ]
