# Generated by Django 4.0.6 on 2022-11-11 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Silis_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(auto_now=True)),
                ('target_product', models.CharField(choices=[('raw material kplus', 'raw material kplus'), ('aa', 'aa')], max_length=100)),
                ('year', models.IntegerField(max_length=4)),
                ('month', models.IntegerField(max_length=2)),
                ('day', models.IntegerField(max_length=2)),
                ('hour', models.IntegerField(max_length=2)),
                ('free_moisture', models.DecimalField(decimal_places=2, max_digits=3)),
                ('crystal_water_rawmat', models.DecimalField(decimal_places=2, max_digits=3)),
                ('purity_rawmat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sio2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
        ),
    ]
