# Generated by Django 4.0.6 on 2022-09-11 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QC_Retest_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(auto_now=True)),
                ('year', models.IntegerField(max_length=4)),
                ('month', models.IntegerField(max_length=2)),
                ('day', models.IntegerField(max_length=2)),
                ('hour', models.IntegerField(max_length=2)),
                ('line', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=10)),
                ('product_silo', models.CharField(choices=[('kenaf', 'kenaf'), ('no product', 'no product'), ('block', 'block')], max_length=40)),
                ('mine', models.CharField(choices=[('mix', 'mix'), ('cheshme', 'cheshme'), ('gorgine', 'gorgine'), ('saran', 'saran')], max_length=40)),
                ('free_moisture', models.DecimalField(decimal_places=2, max_digits=5)),
                ('crystal_water_raw_mat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Purity_raw_mat', models.DecimalField(decimal_places=100, max_digits=1000)),
                ('crystal_water_stucco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Einstrumenge', models.IntegerField()),
                ('Water_gypsum_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('initial_setting_time', models.DecimalField(decimal_places=4, max_digits=7)),
                ('final_setting_time', models.DecimalField(decimal_places=4, max_digits=7)),
                ('Retained_on_63', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Retained_on_200', models.DecimalField(decimal_places=1, max_digits=5)),
                ('Retained_on_500', models.DecimalField(decimal_places=1, max_digits=5)),
                ('non_conformity', models.CharField(max_length=1000)),
                ('actions', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
