# Generated by Django 4.0.6 on 2022-09-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_retest', '0002_rename_retained_on_200_qc_retest_model_retained_on_200_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qc_retest_model',
            name='Purity_raw_mat',
            field=models.DecimalField(decimal_places=10, max_digits=100),
        ),
    ]
