# Generated by Django 4.0.6 on 2023-01-17 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avg_Test_Production_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(auto_now=True)),
                ('year', models.IntegerField(max_length=4)),
                ('month', models.IntegerField(max_length=2)),
                ('day', models.IntegerField(max_length=2)),
                ('line', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=5)),
                ('product_silo', models.CharField(choices=[('B', 'B'), ('K', 'K')], max_length=5)),
                ('usage', models.IntegerField(max_length=3)),
                ('free_moisture', models.DecimalField(decimal_places=2, max_digits=4)),
                ('crystal_water_raw_mat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('purity_of_raw_material', models.DecimalField(decimal_places=2, max_digits=4)),
                ('crystal_water_of_stucco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('einstrumenge', models.DecimalField(decimal_places=1, max_digits=4)),
                ('water_gypsum_ratio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('initial_setting_time', models.DecimalField(decimal_places=4, max_digits=7)),
                ('final_setting_time', models.DecimalField(decimal_places=4, max_digits=7)),
                ('retained_on_63', models.DecimalField(decimal_places=2, max_digits=4)),
                ('retained_on_200', models.DecimalField(decimal_places=2, max_digits=4)),
                ('retained_on_500', models.DecimalField(decimal_places=2, max_digits=4)),
                ('remarks', models.CharField(max_length=10000)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
