# Generated by Django 3.2.3 on 2021-06-30 13:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suger_time0', models.DateTimeField(verbose_name='زمان ریختن شکر')),
                ('suger_time1', models.DateTimeField(verbose_name='زمان اتمام شکر')),
                ('suger_filled_time', models.DurationField(blank=True, null=True, verbose_name='زمان پر شدن')),
                ('suger_weight', models.IntegerField(choices=[(50, 50), (60, 60), (25, 25), (30, 30)], default=50, verbose_name='وزن کیسه شکر')),
                ('suger_per_minute', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('suger_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('remark', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Nealit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تولید نئالیت')),
                ('jumbo_no', models.PositiveIntegerField(unique=True, verbose_name='شماره کیسه')),
                ('jumbo_no_month', models.CharField(max_length=50, verbose_name='شماره ماه کیسه')),
                ('feed_material', models.CharField(choices=[('مواد خام', 'مواد خام'), ('کراشر', 'کراشر'), ('میکس', 'میکس'), ('کناف گچ', 'کناف گچ')], max_length=50, verbose_name='بار ورودی')),
                ('input_temp', models.SmallIntegerField(verbose_name='دمای ورودی')),
                ('output_temp', models.SmallIntegerField(verbose_name='دمای خروجی')),
                ('jumbo_time0', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع جامبو')),
                ('jumbo_time1', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان جامبو')),
                ('jumbo_filled_time', models.DurationField(verbose_name='زمان پر شدن کیسه')),
                ('jumbo_weight', models.PositiveSmallIntegerField(max_length=4, validators=[django.core.validators.MaxLengthValidator(1500, 'عددی کمتر از 1500 قرار دهید')])),
                ('ton_per_hour', models.PositiveSmallIntegerField(verbose_name='تناژ ساعتی')),
                ('ton_per_minute', models.PositiveSmallIntegerField(verbose_name='تناژ دقیقه ای')),
                ('additive_type', models.CharField(max_length=50, verbose_name='نوع افزودنی')),
                ('remark', models.TextField(blank=True, verbose_name='توضیحات')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nealit_author', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.line', verbose_name='خط')),
            ],
        ),
    ]
